### ISSUE TITLE
Code Missing Issue

### ISSUE THREAD

**Issue by santaboi** [adobe-research/ImageFolder#1]
When launching the token inference script, it seems to be some code missing.
The error message indicates that some code is missing in the /tokenizer/tokenizer_image/
`from tokenizer.tokenizer_image.sam import build_sam_vit_encoder_b`
`from tokenizer.tokenizer_image.discriminator_sam import FrozenSamSmallNoDrop`

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest. Please remove these two lines (they are not used in the released version). Please let me know if you are still getting errors.

**Comment by santaboi** [comment]
Thanks for the code release. 
The above error was solved when the 2 import lines were commented out!
