### ISSUE TITLE
Potential HuggingFace Model version mismatch

### ISSUE THREAD

**Issue by santaboi** [adobe-research/ImageFolder#2]
Thanks for the code release!

I've tried to use the HF links provided in the description and they failed.
Therefore, I refer the the XG-GAN repo and download the models from the huggingface there.
The checkpoint I've downloaded is from [https://huggingface.co/qiuk6/XQ-GAN/tree/main/VAR-d17-MSVR10P2-4096](url)
However, after downloading those there seems to be some error with the keyword argument mismatch
when launching the inference command:
`torchrun --nproc_per_node=2 inference.py --infer_ckpt /path/to/ckpt --data_path /path/to/ImageNet --encoder_model vit_base_patch14_dinov2.lvd142m --decoder_model vit_base_patch14_dinov2.lvd142m --product_quant 2 --semantic_guide dinov2 --num_latent_tokens 121 --v_patch_nums 1 1 2 3 3 4 5 6 8 11 --pn 1_1_2_3_3_4_5_6_8_11 --patch_size 11 --sem_half True --cfg 3.25 3.25 --top_k 750 --top_p 0.95
`

**I got the following error of `TypeError: VectorQuantizer2.__init__() got an unexpected keyword argument 'codebook_drop', 'num_latent_tokens'`, `TypeError: VectorQuantizer2.__init__() got an unexpected keyword argument 'codebook_drop'`, and several other argument missing such as `num_latent_tokens` and `test_model`**

It'll be helpful if there is any suggestion to fix this! Thank you!

**Comment by qiuk2** [comment]
Thanks for your kind notice, We have fixed this bug and currently you can follow the guidance of https://github.com/lxa9867/ImageFolder to infer our ckpt! If there is any more questions, please contact us! Appreciated.
